# Hacky secret project 3

trigger:
- main

pr:
- main

jobs:
- job: Build
  strategy:
    matrix:
      mac:
        imageName: 'macos-10.15'
        isMac: True
      win:
        imageName: 'windows-2019'
        isWindows: True
      lin-18:
        imageName: 'ubuntu-18.04'
        isLinux: True
      lin:
        imageName: 'ubuntu-20.04'
        isLinux: True

  pool:
    vmImage: $(imageName)

  steps:
  - checkout: self
    fetchDepth: 1
    # submodules: recursive # can't do submodules here b'cuz depth=1 fails with Github

  - bash: |
      set -e

      sudo apt-get update

      sudo apt-get install -y \
          devscripts \
          libxcb-cursor-dev \
          libxcb-keysyms1-dev \
          libxcb-util-dev \
          libxkbcommon-dev \
          libxkbcommon-x11-dev \
          ninja-build \
          xcb \
          libgtk-3-dev \
          libwebkit2gtk-4.0 \
          libwebkit2gtk-4.0-dev \
          libcurl4-openssl-dev \
          alsa \
          alsa-tools \
          libasound2-dev \
          libjack-dev \
          libfreetype6-dev \
          libxinerama-dev \
          libxcb-xinerama0 \
          libxinerama1 \
          x11proto-xinerama-dev \
          libxrandr-dev \
          libgl1-mesa-dev \
          libxcursor-dev \
          libxcursor1 \
          libxcb-cursor-dev \
          libxcb-cursor0

    condition: variables.isLinux
    displayName: linux - run apt-get


  - bash: |
      git submodule update --init --recursive
    displayName: Get SubModules

  - bash: |
      cmake -Bbuild
    displayName: Run CMake

  - bash: |
      cmake --build build --config Debug --target sc3-installer
    displayName: Build sc3-installer

  - bash: |
      ./build/products/sc3-test
    displayName: Run Tests SC3

