# Hacky secret project 3

trigger:
- main

pr:
- main

jobs:
- job: Build
  strategy:
    matrix:
      mac:
        imageName: 'macos-10.15'
        isMac: True
        cmakeTarget: shortcircuit3py
      win:
        imageName: 'windows-2019'
        isWindows: True
        cmakeTarget: shortcircuit-core
      lin:
        imageName: 'ubuntu-20.04'
        isLinux: True
        cmakeTarget: shortcircuit3py

  pool:
    vmImage: $(imageName)

  steps:
  - checkout: self
    fetchDepth: 1
    # submodules: recursive # can't do submodules here b'cuz depth=1 fails with Github

  - bash: |
      set -e

      sudo apt-get update

      sudo apt-get install -y \
          devscripts \
          libxcb-cursor-dev \
          libxcb-keysyms1-dev \
          libxcb-util-dev \
          libxkbcommon-dev \
          libxkbcommon-x11-dev \
          ninja-build \
          xcb 

        # These are the JUCE deps
        sudo apt-get install -y libgtk-3-dev
        sudo apt-get install -y libwebkit2gtk-4.0
        sudo apt-get install -y libwebkit2gtk-4.0-dev
        sudo apt-get install -y libcurl4-openssl-dev
        sudo apt-get install -y alsa
        sudo apt-get install -y alsa-tools
        sudo apt-get install -y libasound2-dev
        sudo apt-get install -y libjack-dev
        sudo apt-get install -y libfreetype6-dev
        sudo apt-get install -y libxinerama-dev
        sudo apt-get install -y libxcb-xinerama0
        sudo apt-get install -y libxinerama1
        sudo apt-get install -y x11proto-xinerama-dev
        sudo apt-get install -y libxrandr-dev
        sudo apt-get install -y libgl1-mesa-dev
        sudo apt-get install -y libxcursor-dev
        sudo apt-get install -y libxcursor1
        sudo apt-get install -y libxcb-cursor-dev
        sudo apt-get install -y libxcb-cursor0
        sudo apt-get install -y --fix-missing

    condition: variables.isLinux
    displayName: linux - run apt-get


  - bash: |
      git submodule update --init --recursive
    displayName: Get SubModules

  - bash: |
      cmake -Bbuild
    displayName: Run CMake

  - bash: |
      cmake --build build --config Debug --target $(cmakeTarget)
    displayName: Build SC3



  - bash: |
      cmake --build build --config Debug --target sc3-products
      ./build/products/sc3-test

    displayName: Build and Run Tests SC3

