use warnings;

open( IN, "< src/interaction_parameters.h" ) || die "Run from root";
open( INV, "< src/sampler_wrapper_actiondata.h" ) || die "Run from root";
open( OUT, "> src/wrapper_msg_to_string.h" ) || die "Can't make wrapper_msg";

print OUT <<EOD;
/*This file is autogenerated by scripts/make_ip_vga_to-txt.pl. Do not edit*/

#include "interaction_parameters.h"
#include "sampler_wrapper_actiondata.h"

inline std::string debug_wrapper_ip_to_string(int in)
{
    switch (in)
    {
EOD


$going = 0;
while( <IN> )
{
    if( $going && m/^\s+(ip_\S+),/)
    {
        print OUT "    case $1:\n        return \"$1\";\n";
    }
    $going = 1 if( m/enum/ );
    $going = 0 if( m/\}/ );
}

print OUT <<EOD;
    }
    return std::string("unknown ip_ ") + std::to_string(in);
}

inline std::string debug_wrapper_vga_to_string(int in)
{
    switch (in)
    {
EOD

$going = 0;
while( <INV> )
{
    if( $going && m/^\s+(vga_\S+),/)
    {
        print OUT "    case $1:\n        return \"$1\";\n";
    }
    $going = 1 if( m/enum/ );
    $going = 0 if( m/\}/ );
}

print OUT <<EOD;
    }

    return std::string("unknown vga_ ") + std::to_string(in);
}
EOD
