
#error THIS FILE IS UNUSED AND SHOULD NOT COMPILE

//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by scpb.rc
//
#define IDB_BG 101
#define IDB_BITMAP1 102
#define IDB_SLIDERHEAD 102
#define IDB_BITMAP2 103
#define IDB_SLIDERBODY 103
#define IDB_BITMAP3 104
#define IDB_FADERH_BG_BLACK 104
#define IDB_BITMAP4 105
#define IDB_FADERH_BG_BLACK_BP 105
#define IDB_BITMAP5 106
#define IDB_FADERH_BG_WHITE 106
#define IDB_BITMAP6 107
#define IDB_FADERH_BG_WHITE_BP 107
#define IDB_BITMAP7 108
#define IDB_FADERH_HANDLE_BLACK 108
#define IDB_BITMAP8 109
#define IDB_FADERH_HANDLE_MOD 109
#define IDB_BITMAP9 110
#define IDB_FADERH_HANDLE_WHITE 110
#define IDB_BITMAP10 111
#define IDB_FADERV_BG 111
#define IDB_BITMAP11 112
#define IDB_VF 112
#define IDB_FADERV_BG_BP 112
#define IDB_BITMAP12 113
#define IDB_FADERV_HANDLE_BLACK 113
#define IDB_BITMAP13 114
#define IDB_FADERV_HANDLE_MOD 114
#define IDB_BITMAP14 115
#define IDB_FADERV_HANDLE_WHITE 115
#define IDB_BITMAP15 116
#define IDB_ARROWS 116
#define IDR_PNG1 118

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE 119
#define _APS_NEXT_COMMAND_VALUE 40001
#define _APS_NEXT_CONTROL_VALUE 1001
#define _APS_NEXT_SYMED_VALUE 101
#endif
#endif
//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by vtgiurc.rc

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE 101
#define _APS_NEXT_COMMAND_VALUE 40001
#define _APS_NEXT_CONTROL_VALUE 1001
#define _APS_NEXT_SYMED_VALUE 101
#endif
#endif
